version: "2"
services:
  backend:
    build: backend
    volumes:
      - ./backend/package.json:/usr/app/package.json:ro
      - ./backend/dummy_data_importer.js:/usr/app/dummy_data_importer.js:ro
      - ./backend/notification_handler.js:/usr/app/notification_handler.js:ro
      - ./backend/config.js:/usr/app/config.js:ro
      - ./.eslintrc.json:/usr/app/.eslintrc.json:ro
    environment:
      - FIREBASE_ADMIN_PRIVATE_KEY
      - TWILIO_NUMBER
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
  frontend:
    build: frontend
    volumes:
      - ./frontend/cfg:/usr/app/cfg:ro
      - ./frontend/src:/usr/app/src:ro
      - ./frontend/package.json:/usr/app/package.json:ro
      - ./frontend/server.js:/usr/app/server.js:ro
      - ./frontend/webpack.config.js:/usr/app/webpack.config.js:ro
      - ./.babelrc:/usr/app/.babelrc:ro
      # For linting.
      - ./.eslintrc.json:/usr/app/.eslintrc.json:ro
      - ./.eslintignore:/usr/app/.eslintignore:ro
      # Firebase
      - ./frontend/.firebaserc:/usr/app/.firebaserc:ro
      - ./frontend/firebase.json:/usr/app/firebase.json:ro
      - ./frontend/database.rules.json:/usr/app/database.rules.json:ro
    ports:
      - "3005:80"
    environment:
      - FIREBASE_TOKEN

  data-preparation:
      image: data-preparation
      build:
        context: .
        dockerfile: ./data_analysis/Dockerfile
      command: start-notebook.sh --NotebookApp.token=''
      ports:
        - 8888:8889
      volumes:
        - ./:/home/jovyan/work:rw
      environment:
        - PYTHONPATH=/home/jovyan/work
