version: "2"
services:
  frontend:
    build: frontend
    volumes:
      - ./frontend/cfg:/usr/app/cfg:ro
      - ./frontend/src:/usr/app/src:ro
      - ./frontend/package.json:/usr/app/package.json:ro
      - ./frontend/server.js:/usr/app/server.js:ro
      - ./frontend/webpack.config.js:/usr/app/webpack.config.js:ro
      - ./.babelrc:/usr/app/.babelrc:ro
      # For linting.
      - ./.eslintrc.json:/usr/app/.eslintrc.json:ro
      - ./.eslintignore:/usr/app/.eslintignore:ro
      # Firebase
      - ./frontend/.firebaserc:/usr/app/.firebaserc:ro
      - ./frontend/firebase.json:/usr/app/firebase.json:ro
      - ./frontend/database.rules.json:/usr/app/database.rules.json:ro
    ports:
      - "3005:80"
    environment:
      - FIREBASE_TOKEN

  backend:
      image: backend
      build:
        context: .
        dockerfile: Dockerfile.backend
      command: start-notebook.sh --NotebookApp.token=''
      ports:
        - 8888:8888
      volumes: 
        - ./:/home/jovyan/work:rw
      environment:
        - PYTHONPATH=/home/jovyan/work
