version: "2"
services:
  frontend:
    build: frontend
    volumes:
      - ./frontend/cfg:/usr/app/cfg:ro
      - ./frontend/src:/usr/app/src:ro
      - ./frontend/package.json:/usr/app/package.json:ro
      - ./frontend/server.js:/usr/app/server.js:ro
      - ./frontend/webpack.config.js:/usr/app/webpack.config.js:ro
      - ./.babelrc:/usr/app/.babelrc:ro
      # For linting.
      - ./.eslintrc.json:/usr/app/.eslintrc.json:ro
      - ./.eslintignore:/usr/app/.eslintignore:ro
    ports:
      - "3005:80"
    environment:
      - FIREBASE_TOKEN
